# Generated by Django 6.0.5 on 2026-05-08 19:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_add_post_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_mode',
            field=models.BooleanField(db_index=True, default=True, help_text='Hide username and use anonymous ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hide_from_search',
            field=models.BooleanField(db_index=True, default=False, help_text="Don't appear in browse results"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Year of study (1-6)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['from_user', 'created_at'], name='dating_like_from_us_1ee41b_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['to_user', 'created_at'], name='dating_like_to_user_ecd4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'created_at'], name='dating_matc_user1_i_fe4eae_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'created_at'], name='dating_matc_user2_i_ae1784_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagallery',
            index=models.Index(fields=['user', 'created_at'], name='dating_medi_user_id_efd8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagallery',
            index=models.Index(fields=['media_type', 'created_at'], name='dating_medi_media_t_b055ed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='dating_mess_match_i_112d41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'read', 'created_at'], name='dating_mess_match_i_768946_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='dating_post_user_id_b05295_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='dating_post_created_ee7931_idx'),
        ),
    ]
